//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORO.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingcartdetail
    {
        public int id { get; set; }
        public string pkid { get; set; }
        public Nullable<int> itemid { get; set; }
        public string shoppingcartpkid { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> price_tax_included { get; set; }
        public string discount_description { get; set; }
        public Nullable<decimal> discount_percentage { get; set; }
        public Nullable<decimal> discount_price { get; set; }
        public Nullable<decimal> discount_tax { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<decimal> original_tax { get; set; }
        public Nullable<decimal> crv { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
    }
}
