//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodStuffVending
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_MoMoney
    {
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<double> CurrentCash { get; set; }
        public string UploadHistory { get; set; }
        public Nullable<int> itemIncrement { get; set; }
        public Nullable<int> salesIncrement { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
    }
}
