//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodStuffVending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int categoryID { get; set; }
        public int kioskID { get; set; }
        public string categoryName { get; set; }
        public string categoryDescription { get; set; }
        public System.DateTime creationDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
    }
}
