//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodStuffVending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int inventoryID { get; set; }
        public string name { get; set; }
        public string barcode { get; set; }
        public System.DateTime dateEntered { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> tax { get; set; }
        public string category { get; set; }
        public Nullable<double> crv { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> uniqueInsertID { get; set; }
    }
}
