//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodStuffVending
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public int serviceID { get; set; }
        public System.DateTime serviceDate { get; set; }
        public string serviceByUser { get; set; }
        public string inventoryServiced { get; set; }
        public int kioskID { get; set; }
    }
}
