//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodStuffVending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int stockID { get; set; }
        public int inventoryID { get; set; }
        public int kioskID { get; set; }
        public int countOnShelf { get; set; }
        public string area { get; set; }
        public int totalCountSold { get; set; }
        public int incrementSold { get; set; }
        public int weeklyGoal { get; set; }
        public System.DateTime dateEntered { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> crv { get; set; }
        public string category { get; set; }
        public Nullable<bool> isUnit { get; set; }
        public Nullable<bool> isCase { get; set; }
        public Nullable<int> maximum { get; set; }
        public Nullable<int> minimum { get; set; }
        public Nullable<int> SuggestionToStock { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<bool> isVisible { get; set; }
    }
}
