//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodStuffVending
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string phone { get; set; }
        public string empNum { get; set; }
        public string email { get; set; }
        public Nullable<double> bank { get; set; }
        public string pin { get; set; }
        public Nullable<int> itemIncrement { get; set; }
        public Nullable<decimal> salesIncrement { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<int> kioskID { get; set; }
    }
}
