//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deOROImageMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string ID { get; set; }
        public string UPC { get; set; }
        public string Item_Description { get; set; }
        public string Manufacturer { get; set; }
        public string Brand { get; set; }
        public string Distributor { get; set; }
        public string GS1_Category { get; set; }
        public string Pkg_Manufacturer { get; set; }
        public string Pkg_Manufacturer_Address { get; set; }
        public string Pkg_Manufacturer_Phone { get; set; }
        public string Pkg_Manufacturer_Email { get; set; }
        public string Pkg_Manufacturer_URL { get; set; }
        public string Pkg_Distributor { get; set; }
        public string Pkg_Distributor_Address { get; set; }
        public string Pkg_Distributor_Phone { get; set; }
        public string Pkg_Distributor_Email { get; set; }
        public string Pkg_Distributor_URL { get; set; }
        public string Marketing_Description { get; set; }
        public string Other_Description { get; set; }
        public string Units_In_Package { get; set; }
        public string Packaging_Type { get; set; }
        public string Packaging_Size { get; set; }
        public string Package_Information { get; set; }
        public string Created { get; set; }
        public string Last_Updated { get; set; }
    }
}
