//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert
    {
        public int id { get; set; }
        public Nullable<int> metricid { get; set; }
        public string name { get; set; }
        public string frequency { get; set; }
        public string period { get; set; }
        public Nullable<System.DateTime> last_run_date { get; set; }
        public Nullable<System.DateTime> next_run_date { get; set; }
        public string status { get; set; }
        public Nullable<byte> is_active { get; set; }
        public string report_type { get; set; }
    }
}
