//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_reconciliation
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> locationid { get; set; }
        public string cashcollectionpkid { get; set; }
        public Nullable<decimal> coin_total { get; set; }
        public Nullable<int> c1_total { get; set; }
        public Nullable<int> c2_total { get; set; }
        public Nullable<int> c5_total { get; set; }
        public Nullable<int> c10_total { get; set; }
        public Nullable<int> c20_total { get; set; }
        public Nullable<int> c50_total { get; set; }
        public Nullable<int> c100_total { get; set; }
        public Nullable<decimal> total { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
    }
}
