//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class combo_discount_detail
    {
        public int id { get; set; }
        public Nullable<int> combodiscountid { get; set; }
        public Nullable<int> entityid { get; set; }
    }
}
