//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class deORO_MasterEntities : DbContext
    {
        public deORO_MasterEntities()
            : base("name=deORO_MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<shoppingcart> shoppingcarts { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<users_deleted> users_deleted { get; set; }
        public DbSet<dashboard> dashboards { get; set; }
        public DbSet<widget> widgets { get; set; }
        public DbSet<driver> drivers { get; set; }
        public DbSet<schedule> schedules { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<metric> metrics { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<synclog> synclogs { get; set; }
        public DbSet<cash_status> cash_status { get; set; }
        public DbSet<cash_counter> cash_counter { get; set; }
        public DbSet<cash_dispense> cash_dispense { get; set; }
        public DbSet<cash_collection> cash_collection { get; set; }
        public DbSet<manufacturer> manufacturers { get; set; }
        public DbSet<shoppingcartdetail> shoppingcartdetails { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<cash_reconciliation> cash_reconciliation { get; set; }
        public DbSet<webuser> webusers { get; set; }
        public DbSet<location_combo_discount> location_combo_discount { get; set; }
        public DbSet<combo_discount_detail> combo_discount_detail { get; set; }
        public DbSet<location_credit> location_credit { get; set; }
        public DbSet<location_credit_user> location_credit_user { get; set; }
        public DbSet<location_credit_activity> location_credit_activity { get; set; }
        public DbSet<location_service> location_service { get; set; }
        public DbSet<transaction_error> transaction_error { get; set; }
        public DbSet<schedule_detail_item> schedule_detail_item { get; set; }
        public DbSet<location_item_deleted> location_item_deleted { get; set; }
        public DbSet<subsidy_detail> subsidy_detail { get; set; }
        public DbSet<combo_discount> combo_discount { get; set; }
        public DbSet<discount> discounts { get; set; }
        public DbSet<subsidy> subsidies { get; set; }
        public DbSet<accountbalancehistory> accountbalancehistories { get; set; }
        public DbSet<location_subsidy> location_subsidy { get; set; }
        public DbSet<location_item> location_item { get; set; }
        public DbSet<device_error> device_error { get; set; }
        public DbSet<planogram> planograms { get; set; }
        public DbSet<planogram_item> planogram_item { get; set; }
        public DbSet<schedule_detail> schedule_detail { get; set; }
        public DbSet<alert> alerts { get; set; }
        public DbSet<alert_subscription> alert_subscription { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<event_log> event_log { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<user_snapshot> user_snapshot { get; set; }
    }
}
