//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class location_credit
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> locationid { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> expiry { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<byte> is_active { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
        public string created_by { get; set; }
    }
}
