//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_detail_item
    {
        public int id { get; set; }
        public Nullable<int> scheduledetailid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> quantity_at_schedule { get; set; }
        public Nullable<int> quantity_to_refill { get; set; }
        public Nullable<int> over_under { get; set; }
        public string tote { get; set; }
        public string status { get; set; }
    }
}
