//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_detail
    {
        public int id { get; set; }
        public Nullable<int> scheduleid { get; set; }
        public string driverid { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> locationid { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> status_updated_date_time { get; set; }
        public Nullable<int> count { get; set; }
        public string excluded_categories { get; set; }
        public string excluded_planograms { get; set; }
    }
}
