//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsidy
    {
        public int id { get; set; }
        public string category { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public Nullable<decimal> percent { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<byte> is_active { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
        public Nullable<System.DateTime> modified_date_time { get; set; }
    }
}
