//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class help
    {
        public int id { get; set; }
        public string key { get; set; }
        public string title { get; set; }
        public string help_text { get; set; }
        public string video { get; set; }
    }
}
