//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class planogram_item
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<int> order { get; set; }
        public string data { get; set; }
    }
}
