//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion_user
    {
        public int id { get; set; }
        public Nullable<int> promotionid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> purchased { get; set; }
        public Nullable<int> redeemed { get; set; }
    }
}
