//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORODataAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync_data
    {
        public int id { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
