//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deOROWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("deOROWeb.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Customers.
        /// </summary>
        public static string AllCustomers {
            get {
                return ResourceManager.GetString("AllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Locations.
        /// </summary>
        public static string AllLocations {
            get {
                return ResourceManager.GetString("AllLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To Refund.
        /// </summary>
        public static string AmountToRefund {
            get {
                return ResourceManager.GetString("AmountToRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Shelf Life.
        /// </summary>
        public static string AverageShelfLife {
            get {
                return ResourceManager.GetString("AverageShelfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Edit.
        /// </summary>
        public static string BatchEdit {
            get {
                return ResourceManager.GetString("BatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Update.
        /// </summary>
        public static string BatchUpdate {
            get {
                return ResourceManager.GetString("BatchUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Pay.
        /// </summary>
        public static string BillPay {
            get {
                return ResourceManager.GetString("BillPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Refill.
        /// </summary>
        public static string BillRefill {
            get {
                return ResourceManager.GetString("BillRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Feed.
        /// </summary>
        public static string CameraFeed {
            get {
                return ResourceManager.GetString("CameraFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Accountability.
        /// </summary>
        public static string CashAccountability {
            get {
                return ResourceManager.GetString("CashAccountability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Accountability Report.
        /// </summary>
        public static string CashAccountabilityReport {
            get {
                return ResourceManager.GetString("CashAccountabilityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Collection.
        /// </summary>
        public static string CashCollection {
            get {
                return ResourceManager.GetString("CashCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Reconciliation.
        /// </summary>
        public static string CashReconciliation {
            get {
                return ResourceManager.GetString("CashReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code.
        /// </summary>
        public static string CategoryCode {
            get {
                return ResourceManager.GetString("CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Pay.
        /// </summary>
        public static string CoinPay {
            get {
                return ResourceManager.GetString("CoinPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Refill.
        /// </summary>
        public static string CoinRefill {
            get {
                return ResourceManager.GetString("CoinRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Refill Cash Box.
        /// </summary>
        public static string CoinRefillCashBox {
            get {
                return ResourceManager.GetString("CoinRefillCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins.
        /// </summary>
        public static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Total.
        /// </summary>
        public static string CoinTotal {
            get {
                return ResourceManager.GetString("CoinTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected.
        /// </summary>
        public static string Collected {
            get {
                return ResourceManager.GetString("Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected Date Time.
        /// </summary>
        public static string CollectedDateTime {
            get {
                return ResourceManager.GetString("CollectedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Category.
        /// </summary>
        public static string ComboCategory {
            get {
                return ResourceManager.GetString("ComboCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Discounts.
        /// </summary>
        public static string ComboDiscounts {
            get {
                return ResourceManager.GetString("ComboDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Activity.
        /// </summary>
        public static string CreditActivity {
            get {
                return ResourceManager.GetString("CreditActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Pay.
        /// </summary>
        public static string CreditCardPay {
            get {
                return ResourceManager.GetString("CreditCardPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Refill.
        /// </summary>
        public static string CreditCardRefill {
            get {
                return ResourceManager.GetString("CreditCardRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Claimed.
        /// </summary>
        public static string CreditClaimed {
            get {
                return ResourceManager.GetString("CreditClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Claimed Date.
        /// </summary>
        public static string CreditClaimedDate {
            get {
                return ResourceManager.GetString("CreditClaimedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Description.
        /// </summary>
        public static string CreditDescription {
            get {
                return ResourceManager.GetString("CreditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRV.
        /// </summary>
        public static string CRV {
            get {
                return ResourceManager.GetString("CRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment.
        /// </summary>
        public static string CustomerPayment {
            get {
                return ResourceManager.GetString("CustomerPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment Report.
        /// </summary>
        public static string CustomerPaymentReport {
            get {
                return ResourceManager.GetString("CustomerPaymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range Bottom 5 Sellers.
        /// </summary>
        public static string DateRangeBottom5Sellers {
            get {
                return ResourceManager.GetString("DateRangeBottom5Sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range Sales.
        /// </summary>
        public static string DateRangeSales {
            get {
                return ResourceManager.GetString("DateRangeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range Top 5 Sellers.
        /// </summary>
        public static string DateRangeTop5Sellers {
            get {
                return ResourceManager.GetString("DateRangeTop5Sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime.
        /// </summary>
        public static string Daytime {
            get {
                return ResourceManager.GetString("Daytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Driver.
        /// </summary>
        public static string DefaultDriver {
            get {
                return ResourceManager.GetString("DefaultDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depletion Level.
        /// </summary>
        public static string DepletionLevel {
            get {
                return ResourceManager.GetString("DepletionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Errors.
        /// </summary>
        public static string DeviceErrors {
            get {
                return ResourceManager.GetString("DeviceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted Amount.
        /// </summary>
        public static string DiscountedAmount {
            get {
                return ResourceManager.GetString("DiscountedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        public static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Planogram.
        /// </summary>
        public static string EditPlanogram {
            get {
                return ResourceManager.GetString("EditPlanogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Report.
        /// </summary>
        public static string ErrorsReport {
            get {
                return ResourceManager.GetString("ErrorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filteredfrom.
        /// </summary>
        public static string filteredfrom {
            get {
                return ResourceManager.GetString("filteredfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullscreen.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Barcode.
        /// </summary>
        public static string HasBarcode {
            get {
                return ResourceManager.GetString("HasBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Range.
        /// </summary>
        public static string HourRange {
            get {
                return ResourceManager.GetString("HourRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string Iforgotmypassword {
            get {
                return ResourceManager.GetString("Iforgotmypassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File Name.
        /// </summary>
        public static string ImageFileName {
            get {
                return ResourceManager.GetString("ImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Categories.
        /// </summary>
        public static string ItemCategories {
            get {
                return ResourceManager.GetString("ItemCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        public static string ItemCategory {
            get {
                return ResourceManager.GetString("ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Count.
        /// </summary>
        public static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Discounts.
        /// </summary>
        public static string ItemDiscounts {
            get {
                return ResourceManager.GetString("ItemDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Reconciliation.
        /// </summary>
        public static string ItemsReconciliation {
            get {
                return ResourceManager.GetString("ItemsReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Sold.
        /// </summary>
        public static string ItemsSold {
            get {
                return ResourceManager.GetString("ItemsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Total.
        /// </summary>
        public static string ItemTotal {
            get {
                return ResourceManager.GetString("ItemTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Bottom Days Sales.
        /// </summary>
        public static string Last30BottomDaysSales {
            get {
                return ResourceManager.GetString("Last30BottomDaysSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days Bottom 5 Sellers.
        /// </summary>
        public static string Last30DaysBottom5Sellers {
            get {
                return ResourceManager.GetString("Last30DaysBottom5Sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days Sales.
        /// </summary>
        public static string Last30DaysSales {
            get {
                return ResourceManager.GetString("Last30DaysSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days Top 5 Sellers.
        /// </summary>
        public static string Last30DaysTop5Sellers {
            get {
                return ResourceManager.GetString("Last30DaysTop5Sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Bottom Days Sales.
        /// </summary>
        public static string Last7BottomDaysSales {
            get {
                return ResourceManager.GetString("Last7BottomDaysSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days Bottom 5 Sellers.
        /// </summary>
        public static string Last7DaysBottom5Sellers {
            get {
                return ResourceManager.GetString("Last7DaysBottom5Sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days Sales.
        /// </summary>
        public static string Last7DaysSales {
            get {
                return ResourceManager.GetString("Last7DaysSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days Top 5 Sellers.
        /// </summary>
        public static string Last7DaysTop5Sellers {
            get {
                return ResourceManager.GetString("Last7DaysTop5Sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Balance Changed Date.
        /// </summary>
        public static string LastBalanceChangedDate {
            get {
                return ResourceManager.GetString("LastBalanceChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Service Date.
        /// </summary>
        public static string LastServiceDate {
            get {
                return ResourceManager.GetString("LastServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        public static string LocationCode {
            get {
                return ResourceManager.GetString("LocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationCredit.
        /// </summary>
        public static string LocationCredit {
            get {
                return ResourceManager.GetString("LocationCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Credits.
        /// </summary>
        public static string LocationCredits {
            get {
                return ResourceManager.GetString("LocationCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Dashboard.
        /// </summary>
        public static string LocationDashboard {
            get {
                return ResourceManager.GetString("LocationDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationItems.
        /// </summary>
        public static string LocationItems {
            get {
                return ResourceManager.GetString("LocationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login User Name.
        /// </summary>
        public static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Refill.
        /// </summary>
        public static string MachineRefill {
            get {
                return ResourceManager.GetString("MachineRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Refill Sales.
        /// </summary>
        public static string MachineRefillSales {
            get {
                return ResourceManager.GetString("MachineRefillSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Refill Sales Report.
        /// </summary>
        public static string MachineRefillSalesReport {
            get {
                return ResourceManager.GetString("MachineRefillSalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Code.
        /// </summary>
        public static string ManufacturerCode {
            get {
                return ResourceManager.GetString("ManufacturerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Name.
        /// </summary>
        public static string ManufacturerName {
            get {
                return ResourceManager.GetString("ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string Manufacturers {
            get {
                return ResourceManager.GetString("Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Items as Pulled.
        /// </summary>
        public static string MarkItemsasPulled {
            get {
                return ResourceManager.GetString("MarkItemsasPulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxvolume.
        /// </summary>
        public static string maxvolume {
            get {
                return ResourceManager.GetString("maxvolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute.
        /// </summary>
        public static string mute {
            get {
                return ResourceManager.GetString("mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance Pay.
        /// </summary>
        public static string MyAccountPay {
            get {
                return ResourceManager.GetString("MyAccountPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Balance Pay.
        /// </summary>
        public static string MyPayrollPay {
            get {
                return ResourceManager.GetString("MyPayrollPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Confirmation.
        /// </summary>
        public static string NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Registration.
        /// </summary>
        public static string NewUserRegistration {
            get {
                return ResourceManager.GetString("NewUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records available.
        /// </summary>
        public static string Norecordsavailable {
            get {
                return ResourceManager.GetString("Norecordsavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sales.
        /// </summary>
        public static string NoSales {
            get {
                return ResourceManager.GetString("NoSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subsidy.
        /// </summary>
        public static string NoSubsidy {
            get {
                return ResourceManager.GetString("NoSubsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string Nothingfound {
            get {
                return ResourceManager.GetString("Nothingfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        public static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Under.
        /// </summary>
        public static string OverUnder {
            get {
                return ResourceManager.GetString("OverUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Under Report.
        /// </summary>
        public static string OverUnderReport {
            get {
                return ResourceManager.GetString("OverUnderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par.
        /// </summary>
        public static string Par {
            get {
                return ResourceManager.GetString("Par", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method By Amount.
        /// </summary>
        public static string PaymentMethodByAmount {
            get {
                return ResourceManager.GetString("PaymentMethodByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method By Item Count.
        /// </summary>
        public static string PaymentMethodByItemCount {
            get {
                return ResourceManager.GetString("PaymentMethodByItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Routing.
        /// </summary>
        public static string PaymentRouting {
            get {
                return ResourceManager.GetString("PaymentRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Report.
        /// </summary>
        public static string PerformanceReport {
            get {
                return ResourceManager.GetString("PerformanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Order.
        /// </summary>
        public static string PickOrder {
            get {
                return ResourceManager.GetString("PickOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Report.
        /// </summary>
        public static string ProfitReport {
            get {
                return ResourceManager.GetString("ProfitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulled.
        /// </summary>
        public static string Pulled {
            get {
                return ResourceManager.GetString("Pulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string PurchaseComplete {
            get {
                return ResourceManager.GetString("PurchaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Abandoned.
        /// </summary>
        public static string PurchaseCompleteChangeAbandoned {
            get {
                return ResourceManager.GetString("PurchaseCompleteChangeAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Dispensed.
        /// </summary>
        public static string PurchaseCompleteDispense {
            get {
                return ResourceManager.GetString("PurchaseCompleteDispense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change To User Account.
        /// </summary>
        public static string PurchaseCompleteMyAccountPay {
            get {
                return ResourceManager.GetString("PurchaseCompleteMyAccountPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity at Schedule.
        /// </summary>
        public static string QuantityatSchedule {
            get {
                return ResourceManager.GetString("QuantityatSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to Refill.
        /// </summary>
        public static string QuantitytoRefill {
            get {
                return ResourceManager.GetString("QuantitytoRefill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reccuring.
        /// </summary>
        public static string Reccuring {
            get {
                return ResourceManager.GetString("Reccuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecommendedPar.
        /// </summary>
        public static string RecommendedPar {
            get {
                return ResourceManager.GetString("RecommendedPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation.
        /// </summary>
        public static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records per page.
        /// </summary>
        public static string Recordsperpage {
            get {
                return ResourceManager.GetString("Recordsperpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Cleared.
        /// </summary>
        public static string RefundCleared {
            get {
                return ResourceManager.GetString("RefundCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Processed.
        /// </summary>
        public static string RefundProcessed {
            get {
                return ResourceManager.GetString("RefundProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Users.
        /// </summary>
        public static string RemoveUsers {
            get {
                return ResourceManager.GetString("RemoveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string repeat {
            get {
                return ResourceManager.GetString("repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ReportsCategory {
            get {
                return ResourceManager.GetString("ReportsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ReportsDescription {
            get {
                return ResourceManager.GetString("ReportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ReportsLocation {
            get {
                return ResourceManager.GetString("ReportsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string ReportsSubCategory {
            get {
                return ResourceManager.GetString("ReportsSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportType.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        public static string Routing {
            get {
                return ResourceManager.GetString("Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Performance Report.
        /// </summary>
        public static string SalesPerformanceReport {
            get {
                return ResourceManager.GetString("SalesPerformanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Date.
        /// </summary>
        public static string ScheduleDate {
            get {
                return ResourceManager.GetString("ScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Name.
        /// </summary>
        public static string ScheduleName {
            get {
                return ResourceManager.GetString("ScheduleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Interval.
        /// </summary>
        public static string ServiceInterval {
            get {
                return ResourceManager.GetString("ServiceInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping CartDetail.
        /// </summary>
        public static string ShoppingCartDetail {
            get {
                return ResourceManager.GetString("ShoppingCartDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart Pkid.
        /// </summary>
        public static string ShoppingCartPkid {
            get {
                return ResourceManager.GetString("ShoppingCartPkid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Feed.
        /// </summary>
        public static string ShowFeed {
            get {
                return ResourceManager.GetString("ShowFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing all.
        /// </summary>
        public static string Showingall {
            get {
                return ResourceManager.GetString("Showingall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing page.
        /// </summary>
        public static string Showingpage {
            get {
                return ResourceManager.GetString("Showingpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Items.
        /// </summary>
        public static string ShowItems {
            get {
                return ResourceManager.GetString("ShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shuffle.
        /// </summary>
        public static string shuffle {
            get {
                return ResourceManager.GetString("shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign me in.
        /// </summary>
        public static string Signmein {
            get {
                return ResourceManager.GetString("Signmein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategories.
        /// </summary>
        public static string SubCategories {
            get {
                return ResourceManager.GetString("SubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategory.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category Code.
        /// </summary>
        public static string SubCategoryCode {
            get {
                return ResourceManager.GetString("SubCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category Name.
        /// </summary>
        public static string SubCategoryName {
            get {
                return ResourceManager.GetString("SubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subisdy Category.
        /// </summary>
        public static string SubisdyCategory {
            get {
                return ResourceManager.GetString("SubisdyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidies.
        /// </summary>
        public static string Subsidies {
            get {
                return ResourceManager.GetString("Subsidies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidized Price.
        /// </summary>
        public static string SubsidizedPrice {
            get {
                return ResourceManager.GetString("SubsidizedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy.
        /// </summary>
        public static string Subsidy {
            get {
                return ResourceManager.GetString("Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable.
        /// </summary>
        public static string Taxable {
            get {
                return ResourceManager.GetString("Taxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Report.
        /// </summary>
        public static string TaxReport {
            get {
                return ResourceManager.GetString("TaxReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thr.
        /// </summary>
        public static string Thr {
            get {
                return ResourceManager.GetString("Thr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time From.
        /// </summary>
        public static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time To.
        /// </summary>
        public static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string Togglenavigation {
            get {
                return ResourceManager.GetString("Togglenavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Profit.
        /// </summary>
        public static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total records.
        /// </summary>
        public static string totalrecords {
            get {
                return ResourceManager.GetString("totalrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Errors.
        /// </summary>
        public static string TransactionErrors {
            get {
                return ResourceManager.GetString("TransactionErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Recommended Par.
        /// </summary>
        public static string UpdateRecommendedPar {
            get {
                return ResourceManager.GetString("UpdateRecommendedPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Barcode.
        /// </summary>
        public static string UserBarcode {
            get {
                return ResourceManager.GetString("UserBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Deleted.
        /// </summary>
        public static string UsersDeleted {
            get {
                return ResourceManager.GetString("UsersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Transactions.
        /// </summary>
        public static string UserTransactions {
            get {
                return ResourceManager.GetString("UserTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View By.
        /// </summary>
        public static string ViewBy {
            get {
                return ResourceManager.GetString("ViewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web User.
        /// </summary>
        public static string WebUser {
            get {
                return ResourceManager.GetString("WebUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Users.
        /// </summary>
        public static string WebUsers {
            get {
                return ResourceManager.GetString("WebUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
