//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deORO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("deORO.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Recycler Status.
        /// </summary>
        internal static string AddMoney_Bill {
            get {
                return ResourceManager.GetString("AddMoney.Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Coin Status.
        /// </summary>
        internal static string AddMoney_Coin {
            get {
                return ResourceManager.GetString("AddMoney.Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Status.
        /// </summary>
        internal static string AddMoney_Refresh {
            get {
                return ResourceManager.GetString("AddMoney.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AddMoney_Status {
            get {
                return ResourceManager.GetString("AddMoney.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string Administration_ApplicationSettings {
            get {
                return ResourceManager.GetString("Administration.ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer.
        /// </summary>
        internal static string Administration_FileTransfer {
            get {
                return ResourceManager.GetString("Administration.FileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftp.
        /// </summary>
        internal static string Administration_Ftp {
            get {
                return ResourceManager.GetString("Administration.Ftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Administration_Items {
            get {
                return ResourceManager.GetString("Administration.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Administration_Service {
            get {
                return ResourceManager.GetString("Administration.Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Administration_Shutdown {
            get {
                return ResourceManager.GetString("Administration.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Info.
        /// </summary>
        internal static string Administration_SyncInfo {
            get {
                return ResourceManager.GetString("Administration.SyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ApplicationSettings_Save {
            get {
                return ResourceManager.GetString("ApplicationSettings.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Log off.
        /// </summary>
        internal static string AutoLogoff_Cancel {
            get {
                return ResourceManager.GetString("AutoLogoff.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been idle for an extended period of time. You have 00:00:{0} to Cancel Auto Logoff..
        /// </summary>
        internal static string AutoLogoff_Message {
            get {
                return ResourceManager.GetString("AutoLogoff.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off Notification.
        /// </summary>
        internal static string AutoLogoff_Title {
            get {
                return ResourceManager.GetString("AutoLogoff.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Barcode.
        /// </summary>
        internal static string Barcode_ChangeBarcode {
            get {
                return ResourceManager.GetString("Barcode.ChangeBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Barcode.
        /// </summary>
        internal static string Barcode_CurrentBarcode {
            get {
                return ResourceManager.GetString("Barcode.CurrentBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Barcode.
        /// </summary>
        internal static string Barcode_NewBarcode {
            get {
                return ResourceManager.GetString("Barcode.NewBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or Scan your Barcode.
        /// </summary>
        internal static string Barcode_Title {
            get {
                return ResourceManager.GetString("Barcode.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Billing_Ok {
            get {
                return ResourceManager.GetString("Billing.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Scan Your Credit Card.
        /// </summary>
        internal static string Billing_PleaseScan {
            get {
                return ResourceManager.GetString("Billing.PleaseScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill Account Using.
        /// </summary>
        internal static string Billing_RefillAccountUsing {
            get {
                return ResourceManager.GetString("Billing.RefillAccountUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Balance.
        /// </summary>
        internal static string Billing_YourAccountBalance {
            get {
                return ResourceManager.GetString("Billing.YourAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT BALANCE.
        /// </summary>
        internal static string Button_AccountBalance {
            get {
                return ResourceManager.GetString("Button.AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Funds.
        /// </summary>
        internal static string Button_Addfunds {
            get {
                return ResourceManager.GetString("Button.Addfunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH.
        /// </summary>
        internal static string Button_Cash {
            get {
                return ResourceManager.GetString("Button.Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT / DEBIT.
        /// </summary>
        internal static string Button_CreditCard {
            get {
                return ResourceManager.GetString("Button.CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAMAGED.
        /// </summary>
        internal static string Button_DamagedBarcode {
            get {
                return ResourceManager.GetString("Button.DamagedBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNTS.
        /// </summary>
        internal static string Button_Discounts {
            get {
                return ResourceManager.GetString("Button.Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        internal static string Button_Logout {
            get {
                return ResourceManager.GetString("Button.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ACCOUNT.
        /// </summary>
        internal static string Button_MyAccount {
            get {
                return ResourceManager.GetString("Button.MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO BARCODE.
        /// </summary>
        internal static string Button_NoBarcode {
            get {
                return ResourceManager.GetString("Button.NoBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLL BALANCE.
        /// </summary>
        internal static string Button_PayrollBalance {
            get {
                return ResourceManager.GetString("Button.PayrollBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string Button_Register {
            get {
                return ResourceManager.GetString("Button.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOPPING.
        /// </summary>
        internal static string Button_Shopping {
            get {
                return ResourceManager.GetString("Button.Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Configured.
        /// </summary>
        internal static string CameraFeed_NotConfigured {
            get {
                return ResourceManager.GetString("CameraFeed.NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string CashPayment_Amount {
            get {
                return ResourceManager.GetString("CashPayment.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string CashPayment_AmountDue {
            get {
                return ResourceManager.GetString("CashPayment.AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in Credit.
        /// </summary>
        internal static string CashPayment_AmountInCredit {
            get {
                return ResourceManager.GetString("CashPayment.AmountInCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        internal static string CashPayment_AmountPaid {
            get {
                return ResourceManager.GetString("CashPayment.AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Transaction.
        /// </summary>
        internal static string CashPayment_CancelTransaction {
            get {
                return ResourceManager.GetString("CashPayment.CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and Credit Change.
        /// </summary>
        internal static string CashPayment_LoginAndCreditChange {
            get {
                return ResourceManager.GetString("CashPayment.LoginAndCreditChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string CashPayment_Source {
            get {
                return ResourceManager.GetString("CashPayment.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string CashRefill_Amount {
            get {
                return ResourceManager.GetString("CashRefill.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CashRefill_Cancel {
            get {
                return ResourceManager.GetString("CashRefill.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string CashRefill_DateTime {
            get {
                return ResourceManager.GetString("CashRefill.DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CashRefill_OK {
            get {
                return ResourceManager.GetString("CashRefill.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string CashRefill_Source {
            get {
                return ResourceManager.GetString("CashRefill.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Refill Amount:.
        /// </summary>
        internal static string CashRefill_TotalRefillAmount {
            get {
                return ResourceManager.GetString("CashRefill.TotalRefillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string ComboDiscounts_Title {
            get {
                return ResourceManager.GetString("ComboDiscounts.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION.
        /// </summary>
        internal static string Config_application {
            get {
                return ResourceManager.GetString("Config.application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARCODE READER.
        /// </summary>
        internal static string Config_barcodereader {
            get {
                return ResourceManager.GetString("Config.barcodereader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL.
        /// </summary>
        internal static string Config_bill {
            get {
                return ResourceManager.GetString("Config.bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMERA FEED.
        /// </summary>
        internal static string Config_camerafeed {
            get {
                return ResourceManager.GetString("Config.camerafeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARD PROCESSOR.
        /// </summary>
        internal static string Config_cardprocessor {
            get {
                return ResourceManager.GetString("Config.cardprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARD READER.
        /// </summary>
        internal static string Config_cardreader {
            get {
                return ResourceManager.GetString("Config.cardreader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COIN.
        /// </summary>
        internal static string Config_coin {
            get {
                return ResourceManager.GetString("Config.coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIL.
        /// </summary>
        internal static string Config_mail {
            get {
                return ResourceManager.GetString("Config.mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFILL REWARDS.
        /// </summary>
        internal static string Config_refillrewards {
            get {
                return ResourceManager.GetString("Config.refillrewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB RELAY.
        /// </summary>
        internal static string Config_usbrelay {
            get {
                return ResourceManager.GetString("Config.usbrelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Credit_Amount {
            get {
                return ResourceManager.GetString("Credit.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to my Account Balance.
        /// </summary>
        internal static string Credit_ApplyToMyAccountBalance {
            get {
                return ResourceManager.GetString("Credit.ApplyToMyAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Credit_Cancel {
            get {
                return ResourceManager.GetString("Credit.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Credit_Description {
            get {
                return ResourceManager.GetString("Credit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string Credit_ExpiryDate {
            get {
                return ResourceManager.GetString("Credit.ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following credits are available for your to redeem.
        /// </summary>
        internal static string Credit_Title {
            get {
                return ResourceManager.GetString("Credit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string CreditCardPayment_AmountDue {
            get {
                return ResourceManager.GetString("CreditCardPayment.AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CreditCardPayment_Cancel {
            get {
                return ResourceManager.GetString("CreditCardPayment.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Reader Error. Please press OK and retry.
        /// </summary>
        internal static string CreditCardPayment_CardReadError {
            get {
                return ResourceManager.GetString("CreditCardPayment.CardReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Purchase.
        /// </summary>
        internal static string CreditCardPayment_DialogTitle {
            get {
                return ResourceManager.GetString("CreditCardPayment.DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter ZipCode and retry.
        /// </summary>
        internal static string CreditCardPayment_ErrorZip {
            get {
                return ResourceManager.GetString("CreditCardPayment.ErrorZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Transaction. Please wait...
        /// </summary>
        internal static string CreditCardPayment_ProcessingTransaction {
            get {
                return ResourceManager.GetString("CreditCardPayment.ProcessingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please swipe your credit card.
        /// </summary>
        internal static string CreditCardPayment_Title {
            get {
                return ResourceManager.GetString("CreditCardPayment.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string CreditCardPayment_Zip {
            get {
                return ResourceManager.GetString("CreditCardPayment.Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CreditCardRefill_Cancel {
            get {
                return ResourceManager.GetString("CreditCardRefill.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string CreditCardRefill_Message {
            get {
                return ResourceManager.GetString("CreditCardRefill.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CreditCardRefill_OK {
            get {
                return ResourceManager.GetString("CreditCardRefill.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option below and press OK.
        /// </summary>
        internal static string CreditCardRefill_Title {
            get {
                return ResourceManager.GetString("CreditCardRefill.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string CreditCardRefill_ZipCode {
            get {
                return ResourceManager.GetString("CreditCardRefill.ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Shopping Cart.
        /// </summary>
        internal static string DamagedBarcode_AddToShoppingCart {
            get {
                return ResourceManager.GetString("DamagedBarcode.AddToShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string DamagedBarcode_Barcode {
            get {
                return ResourceManager.GetString("DamagedBarcode.Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DamagedBarcode_Cancel {
            get {
                return ResourceManager.GetString("DamagedBarcode.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string DamagedBarcode_Category {
            get {
                return ResourceManager.GetString("DamagedBarcode.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text to Filter Items.
        /// </summary>
        internal static string DamagedBarcode_EnterTextToFilterItems {
            get {
                return ResourceManager.GetString("DamagedBarcode.EnterTextToFilterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data. Please wait...
        /// </summary>
        internal static string DamagedBarcode_LoadingData {
            get {
                return ResourceManager.GetString("DamagedBarcode.LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DamagedBarcode_Name {
            get {
                return ResourceManager.GetString("DamagedBarcode.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string DamagedBarcode_Price {
            get {
                return ResourceManager.GetString("DamagedBarcode.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string DamagedBarcode_Select {
            get {
                return ResourceManager.GetString("DamagedBarcode.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string DeleteMe_Address {
            get {
                return ResourceManager.GetString("DeleteMe.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City, State, Zip.
        /// </summary>
        internal static string DeleteMe_CityStateZip {
            get {
                return ResourceManager.GetString("DeleteMe.CityStateZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteMe_Deleted {
            get {
                return ResourceManager.GetString("DeleteMe.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string DeleteMe_Email {
            get {
                return ResourceManager.GetString("DeleteMe.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Cannot be Empty.
        /// </summary>
        internal static string DeleteMe_ErrorAddress {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Cannot be Empty.
        /// </summary>
        internal static string DeleteMe_ErrorCity {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Cannot be Empty.
        /// </summary>
        internal static string DeleteMe_ErrorFirstName {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Cannot be Empty.
        /// </summary>
        internal static string DeleteMe_ErrorLastName {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone.
        /// </summary>
        internal static string DeleteMe_ErrorPhone {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Cannot be Empty.
        /// </summary>
        internal static string DeleteMe_ErrorState {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Zip.
        /// </summary>
        internal static string DeleteMe_ErrorZip {
            get {
                return ResourceManager.GetString("DeleteMe.ErrorZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First / Last Name.
        /// </summary>
        internal static string DeleteMe_FirstLastName {
            get {
                return ResourceManager.GetString("DeleteMe.FirstLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string DeleteMe_Phone {
            get {
                return ResourceManager.GetString("DeleteMe.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account? This action can&apos;t be undone. You must fill the following form so a check can be issued for an amount of {0} which currently is your account balance..
        /// </summary>
        internal static string DeleteMe_Title {
            get {
                return ResourceManager.GetString("DeleteMe.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we dispense change.
        /// </summary>
        internal static string DispenseChange_Message {
            get {
                return ResourceManager.GetString("DispenseChange.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DispenseChange_OK {
            get {
                return ResourceManager.GetString("DispenseChange.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispense Change.
        /// </summary>
        internal static string DispenseChange_Title {
            get {
                return ResourceManager.GetString("DispenseChange.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        internal static string Email_ChangeEmail {
            get {
                return ResourceManager.GetString("Email.ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Email.
        /// </summary>
        internal static string Email_CurrentEmail {
            get {
                return ResourceManager.GetString("Email.CurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string Email_InvalidEmail {
            get {
                return ResourceManager.GetString("Email.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        internal static string Email_NewEmail {
            get {
                return ResourceManager.GetString("Email.NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        internal static string Email_Title {
            get {
                return ResourceManager.GetString("Email.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string FileTransfer_Destination {
            get {
                return ResourceManager.GetString("FileTransfer.Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string FileTransfer_Source {
            get {
                return ResourceManager.GetString("FileTransfer.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string FingerPrint_CultureInfo {
            get {
                return ResourceManager.GetString("FingerPrint.CultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ForgotPassword_Cancel {
            get {
                return ResourceManager.GetString("ForgotPassword.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Password.
        /// </summary>
        internal static string ForgotPassword_EmailPassword {
            get {
                return ResourceManager.GetString("ForgotPassword.EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string ForgotPassword_Error {
            get {
                return ResourceManager.GetString("ForgotPassword.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Items.
        /// </summary>
        internal static string Items_AllItems {
            get {
                return ResourceManager.GetString("Items.AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string Items_Barcode {
            get {
                return ResourceManager.GetString("Items.Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Or Scan Barcode to Filter Items.
        /// </summary>
        internal static string Items_EnterOrScanBarcode {
            get {
                return ResourceManager.GetString("Items.EnterOrScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Items_Name {
            get {
                return ResourceManager.GetString("Items.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over / Under.
        /// </summary>
        internal static string Items_OverUnder {
            get {
                return ResourceManager.GetString("Items.OverUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity After Service.
        /// </summary>
        internal static string Items_QuantityAfterService {
            get {
                return ResourceManager.GetString("Items.QuantityAfterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviced Items.
        /// </summary>
        internal static string Items_ServicedItems {
            get {
                return ResourceManager.GetString("Items.ServicedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stale.
        /// </summary>
        internal static string Items_Stale {
            get {
                return ResourceManager.GetString("Items.Stale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Login_Cancel {
            get {
                return ResourceManager.GetString("Login.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login {
            get {
                return ResourceManager.GetString("Login.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Method.
        /// </summary>
        internal static string Login_LoginMethod {
            get {
                return ResourceManager.GetString("Login.LoginMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan Fingerprint or input User Name / Password to Login.
        /// </summary>
        internal static string Login_Title1 {
            get {
                return ResourceManager.GetString("Login.Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan Barcode to Login.
        /// </summary>
        internal static string Login_Title2 {
            get {
                return ResourceManager.GetString("Login.Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Login_UserName {
            get {
                return ResourceManager.GetString("Login.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello        ///{0}.
        /// </summary>
        internal static string MainWindow_Welcome {
            get {
                return ResourceManager.GetString("MainWindow.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Message_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("Message.DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string Message_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("Message.DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Fingerprint.
        /// </summary>
        internal static string Message_FingerPrintRegistrationTtile {
            get {
                return ResourceManager.GetString("Message.FingerPrintRegistrationTtile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed, Invalid Fingerprint..
        /// </summary>
        internal static string Message_InvalidFingerprintMessage {
            get {
                return ResourceManager.GetString("Message.InvalidFingerprintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Fingerprint.
        /// </summary>
        internal static string Message_InvalidFingerprintTitle {
            get {
                return ResourceManager.GetString("Message.InvalidFingerprintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed, Incorrect user or password..
        /// </summary>
        internal static string Message_LoginFailedMessage {
            get {
                return ResourceManager.GetString("Message.LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string Message_LoginFailedTitle {
            get {
                return ResourceManager.GetString("Message.LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Complete.
        /// </summary>
        internal static string Message_PurchaseComplete {
            get {
                return ResourceManager.GetString("Message.PurchaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint Saved Successfully.
        /// </summary>
        internal static string Message_SuccessfulFingerPrintRegistrationMessage {
            get {
                return ResourceManager.GetString("Message.SuccessfulFingerPrintRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account refill was successful.
        /// </summary>
        internal static string Message_SuccessfulRefillMessage {
            get {
                return ResourceManager.GetString("Message.SuccessfulRefillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Refill.
        /// </summary>
        internal static string Message_SuccessfulRefillTitle {
            get {
                return ResourceManager.GetString("Message.SuccessfulRefillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save Fingerprint.
        /// </summary>
        internal static string Message_UnsuccessfulFingerPrintRegistrationMessage {
            get {
                return ResourceManager.GetString("Message.UnsuccessfulFingerPrintRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MessageBox_Cancel {
            get {
                return ResourceManager.GetString("MessageBox.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string MessageBox_Print {
            get {
                return ResourceManager.GetString("MessageBox.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MissingBarcodeCategories_Cancel {
            get {
                return ResourceManager.GetString("MissingBarcodeCategories.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Category.
        /// </summary>
        internal static string MissingBarcodeCategories_Title {
            get {
                return ResourceManager.GetString("MissingBarcodeCategories.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        internal static string MissingBarcodeItem_AddToCart {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MissingBarcodeItem_Cancel {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string MissingBarcodeItem_ItemName {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string MissingBarcodeItem_ItemPrice {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.ItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quantity.
        /// </summary>
        internal static string MissingBarcodeItem_SelectQuantity {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.SelectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string MissingBarcodeItem_Tax {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        internal static string MissingBarcodeItem_Title {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price (incl. tax).
        /// </summary>
        internal static string MissingBarcodeItem_TotalPrice {
            get {
                return ResourceManager.GetString("MissingBarcodeItem.TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MissingBarcodeItems_Cancel {
            get {
                return ResourceManager.GetString("MissingBarcodeItems.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Item.
        /// </summary>
        internal static string MissingBarcodeItems_Title {
            get {
                return ResourceManager.GetString("MissingBarcodeItems.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string MyAccount_Administration {
            get {
                return ResourceManager.GetString("MyAccount.Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string MyAccount_Barcode {
            get {
                return ResourceManager.GetString("MyAccount.Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string MyAccount_Billing {
            get {
                return ResourceManager.GetString("MyAccount.Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Me.
        /// </summary>
        internal static string MyAccount_DeleteMe {
            get {
                return ResourceManager.GetString("MyAccount.DeleteMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string MyAccount_Email {
            get {
                return ResourceManager.GetString("MyAccount.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprints.
        /// </summary>
        internal static string MyAccount_FingerPrints {
            get {
                return ResourceManager.GetString("MyAccount.FingerPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string MyAccount_Password {
            get {
                return ResourceManager.GetString("MyAccount.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        internal static string MyAccount_TransactionHistory {
            get {
                return ResourceManager.GetString("MyAccount.TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        internal static string MyAccountPay_AccountBalance {
            get {
                return ResourceManager.GetString("MyAccountPay.AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string MyAccountPay_AmountDue {
            get {
                return ResourceManager.GetString("MyAccountPay.AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MyAccountPay_Cancel {
            get {
                return ResourceManager.GetString("MyAccountPay.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MyAccountPay_OK {
            get {
                return ResourceManager.GetString("MyAccountPay.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string MyPayrollPay_AmountDue {
            get {
                return ResourceManager.GetString("MyPayrollPay.AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MyPayrollPay_Cancel {
            get {
                return ResourceManager.GetString("MyPayrollPay.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MyPayrollPay_OK {
            get {
                return ResourceManager.GetString("MyPayrollPay.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Balance.
        /// </summary>
        internal static string MyPayrollPay_PayrollBalance {
            get {
                return ResourceManager.GetString("MyPayrollPay.PayrollBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string NewUser_Cancel {
            get {
                return ResourceManager.GetString("NewUser.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Barcode and Scan.
        /// </summary>
        internal static string NewUser_ClickBarcodeAndScan {
            get {
                return ResourceManager.GetString("NewUser.ClickBarcodeAndScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string NewUser_ConfirmPassword {
            get {
                return ResourceManager.GetString("NewUser.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string NewUser_DOB {
            get {
                return ResourceManager.GetString("NewUser.DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the calendar!.
        /// </summary>
        internal static string NewUser_DOBTexblock {
            get {
                return ResourceManager.GetString("NewUser.DOBTexblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string NewUser_Email {
            get {
                return ResourceManager.GetString("NewUser.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string NewUser_FirstName {
            get {
                return ResourceManager.GetString("NewUser.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string NewUser_Gender {
            get {
                return ResourceManager.GetString("NewUser.Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string NewUser_LastName {
            get {
                return ResourceManager.GetString("NewUser.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string NewUser_Password {
            get {
                return ResourceManager.GetString("NewUser.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string NewUser_Register {
            get {
                return ResourceManager.GetString("NewUser.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Registration.
        /// </summary>
        internal static string NewUser_Title {
            get {
                return ResourceManager.GetString("NewUser.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string NewUser_UserName {
            get {
                return ResourceManager.GetString("NewUser.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Password_ChangePassword {
            get {
                return ResourceManager.GetString("Password.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Password_ConfirmPassword {
            get {
                return ResourceManager.GetString("Password.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string Password_NewPassword {
            get {
                return ResourceManager.GetString("Password.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Password_Title {
            get {
                return ResourceManager.GetString("Password.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        internal static string PaymentOptions_Account_Balance {
            get {
                return ResourceManager.GetString("PaymentOptions.Account Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Balance.
        /// </summary>
        internal static string PaymentOptions_Payroll_Balance {
            get {
                return ResourceManager.GetString("PaymentOptions.Payroll Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Options.
        /// </summary>
        internal static string PaymentOptions_Title {
            get {
                return ResourceManager.GetString("PaymentOptions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Popup_Close {
            get {
                return ResourceManager.GetString("Popup.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint Registration.
        /// </summary>
        internal static string Register_FingerprintHeader {
            get {
                return ResourceManager.GetString("Register.FingerprintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Register_FingerprintSaveButton {
            get {
                return ResourceManager.GetString("Register.FingerprintSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account and Credit Change.
        /// </summary>
        internal static string ReturnChangeOptions_CreateAccountAndCreditChange {
            get {
                return ResourceManager.GetString("ReturnChangeOptions.CreateAccountAndCreditChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Change to My Account.
        /// </summary>
        internal static string ReturnChangeOptions_CreditChangeToMyAccount {
            get {
                return ResourceManager.GetString("ReturnChangeOptions.CreditChangeToMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispense Change.
        /// </summary>
        internal static string ReturnChangeOptions_DispenseChange {
            get {
                return ResourceManager.GetString("ReturnChangeOptions.DispenseChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and Credit Change.
        /// </summary>
        internal static string ReturnChangeOptions_LoginAndCreditChange {
            get {
                return ResourceManager.GetString("ReturnChangeOptions.LoginAndCreditChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change.
        /// </summary>
        internal static string ReturnChangeOptions_NoChange {
            get {
                return ResourceManager.GetString("ReturnChangeOptions.NoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a registered User, Please Login to Credit ${0} to your Account Or Click on one of the following options. If you fail to do so, you will lose the ${0} in credit.
        /// </summary>
        internal static string ReturnChangeOptions_Title {
            get {
                return ResourceManager.GetString("ReturnChangeOptions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Money.
        /// </summary>
        internal static string Service_AddMoney {
            get {
                return ResourceManager.GetString("Service.AddMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Collected.
        /// </summary>
        internal static string Service_CashCollected {
            get {
                return ResourceManager.GetString("Service.CashCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Service.
        /// </summary>
        internal static string Service_LocationService {
            get {
                return ResourceManager.GetString("Service.LocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Items.
        /// </summary>
        internal static string Service_ManageItems {
            get {
                return ResourceManager.GetString("Service.ManageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Service_Off {
            get {
                return ResourceManager.GetString("Service.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Service_OK {
            get {
                return ResourceManager.GetString("Service.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Service_On {
            get {
                return ResourceManager.GetString("Service.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Service.
        /// </summary>
        internal static string Service_ResetService {
            get {
                return ResourceManager.GetString("Service.ResetService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Complete.
        /// </summary>
        internal static string Service_ServiceComplete {
            get {
                return ResourceManager.GetString("Service.ServiceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Start.
        /// </summary>
        internal static string Service_ServiceStart {
            get {
                return ResourceManager.GetString("Service.ServiceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Motor.
        /// </summary>
        internal static string Service_TestMotor {
            get {
                return ResourceManager.GetString("Service.TestMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Kiosk.
        /// </summary>
        internal static string Service_UnlockKiosk {
            get {
                return ResourceManager.GetString("Service.UnlockKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ShoppingCart_Barcode {
            get {
                return ResourceManager.GetString("ShoppingCart.Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Discount Applied.
        /// </summary>
        internal static string ShoppingCart_ComboDiscountApplied {
            get {
                return ResourceManager.GetString("ShoppingCart.ComboDiscountApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRV.
        /// </summary>
        internal static string ShoppingCart_CRV {
            get {
                return ResourceManager.GetString("ShoppingCart.CRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string ShoppingCart_Discount {
            get {
                return ResourceManager.GetString("ShoppingCart.Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Savings.
        /// </summary>
        internal static string ShoppingCart_DiscountSavings {
            get {
                return ResourceManager.GetString("ShoppingCart.DiscountSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ShoppingCart_Name {
            get {
                return ResourceManager.GetString("ShoppingCart.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price.
        /// </summary>
        internal static string ShoppingCart_OriginalPrice {
            get {
                return ResourceManager.GetString("ShoppingCart.OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ShoppingCart_Price {
            get {
                return ResourceManager.GetString("ShoppingCart.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy.
        /// </summary>
        internal static string ShoppingCart_Subsidy {
            get {
                return ResourceManager.GetString("ShoppingCart.Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy Savings.
        /// </summary>
        internal static string ShoppingCart_SubsidySavings {
            get {
                return ResourceManager.GetString("ShoppingCart.SubsidySavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string ShoppingCart_Tax {
            get {
                return ResourceManager.GetString("ShoppingCart.Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ShoppingCart_Total {
            get {
                return ResourceManager.GetString("ShoppingCart.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Data in progress. Please wait...
        /// </summary>
        internal static string SyncData_Message {
            get {
                return ResourceManager.GetString("SyncData.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string SyncInfo_DateTime {
            get {
                return ResourceManager.GetString("SyncInfo.DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SyncInfo_Description {
            get {
                return ResourceManager.GetString("SyncInfo.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Download Date.
        /// </summary>
        internal static string SyncInfo_LastDownloadDate {
            get {
                return ResourceManager.GetString("SyncInfo.LastDownloadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Download Status.
        /// </summary>
        internal static string SyncInfo_LastDownloadStatus {
            get {
                return ResourceManager.GetString("SyncInfo.LastDownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Upload Date.
        /// </summary>
        internal static string SyncInfo_LastUploadDate {
            get {
                return ResourceManager.GetString("SyncInfo.LastUploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Upload Status.
        /// </summary>
        internal static string SyncInfo_LastUploadStatus {
            get {
                return ResourceManager.GetString("SyncInfo.LastUploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string SyncInfo_Message {
            get {
                return ResourceManager.GetString("SyncInfo.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SyncInfo_Save {
            get {
                return ResourceManager.GetString("SyncInfo.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Data.
        /// </summary>
        internal static string SyncInfo_SyncData {
            get {
                return ResourceManager.GetString("SyncInfo.SyncData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SyncInfo_Type {
            get {
                return ResourceManager.GetString("SyncInfo.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Credit Card Account Password.
        /// </summary>
        internal static string SyncInfo_UpdateCreditCardAccountPassword {
            get {
                return ResourceManager.GetString("SyncInfo.UpdateCreditCardAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TransactionHistory_Amount {
            get {
                return ResourceManager.GetString("TransactionHistory.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Dates.
        /// </summary>
        internal static string TransactionHistory_ApplyDates {
            get {
                return ResourceManager.GetString("TransactionHistory.ApplyDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TransactionHistory_DateTime {
            get {
                return ResourceManager.GetString("TransactionHistory.DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text to Filter Items.
        /// </summary>
        internal static string TransactionHistory_EnterTextToFilterItems {
            get {
                return ResourceManager.GetString("TransactionHistory.EnterTextToFilterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string TransactionHistory_FromDate {
            get {
                return ResourceManager.GetString("TransactionHistory.FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string TransactionHistory_ToDate {
            get {
                return ResourceManager.GetString("TransactionHistory.ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TransactionHistory_Type {
            get {
                return ResourceManager.GetString("TransactionHistory.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string TransactionHistory_UserName {
            get {
                return ResourceManager.GetString("TransactionHistory.UserName", resourceCulture);
            }
        }
    }
}
